### ISSUE TITLE
Plus de nombres

### ISSUE THREAD

**Issue by TheCactusVert** [MisterRobot42/PedantixHelper#1]
Il faudrait qur le script entre tous les nombres de 0 à 2023 afin de tester toutes les dates possibles. Et éventuellement les nombres inférieur s à 0 jusqu'au dinosaures.

Cordialement XOXO

**Comment by MisterRobot42** [comment]
Cher XOXO,

Merci beaucoup pour votre recommandation ! Votre idée de tester toutes les dates possibles, y compris celles remontant jusqu'aux dinosaures, est tout simplement géniale. Cependant, j'ai quelques préoccupations :

* En supposant que le script teste un nombre par seconde, il nous faudrait près de 34 minutes pour couvrir tous les nombres jusqu'à 2023, sans même mentionner l'époque des dinosaures. Je crains que votre patience ne soit mise à rude épreuve !
* Si nous allions jusqu'au début de l'ère des dinosaures, nous serions en 230 millions d'années avant JC, ce qui nous donnerait environ 7,253 milliards de secondes de travail supplémentaires, soit une excursion de 230 ans. Pas sûr que nous ayons tout ce temps devant nous !

Néanmoins, si vous êtes vraiment attaché à l'idée des dinosaures, je vous recommande d'ajouter une fonctionnalité supplémentaire à votre script qui remplacera la liste des nombres par des noms de dinosaures célèbres. Cela ajoutera une touche préhistorique à votre jeu et pourrait même faire sourire quelques paléontologues passionnés.

Je vous souhaite beaucoup de plaisir avec votre script et de joyeuses découvertes sur ce jeu ! Si vous avez d'autres idées farfelues, n'hésitez pas à les partager.

Jurassiquement vôtre,

Mr Robot

**Comment by TheCactusVert** [comment]
Thank you my dear sir.
